
enum TestStatus { BEFORE_START, SHOW_QUESTION, SHOW_ANSWER, FINISHED }

enum SERIES {
  ALL,
  EASTBLUE,
  ALABASTA,
  SKYISLAND,
  WATERSEVEN,
  THRILLERBARK,
  IMPELDOWN,
  FISHMANISLAND,
  DRESSROSA,
  WHOLECAKEISLAND,
  WANOKUNI,
}